/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package fr.nom.cure.specialt;

public final class R {
    public static final class array {
        public static final int tea=0x7f050000;
    }
    public static final class attr {
    }
    public static final class id {
        public static final int comments=0x7f060005;
        public static final int group1=0x7f060001;
        public static final int infusion=0x7f060004;
        public static final int master=0x7f060002;
        public static final int my=0x7f060003;
        public static final int save=0x7f060006;
        public static final int teaName=0x7f060000;
    }
    public static final class layout {
        public static final int detail_tea=0x7f020000;
        public static final int main=0x7f020001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class xml {
        public static final int menu=0x7f030000;
    }
}
